# scale

include ../../examples.mk

## standalone: run invasion percolation
standalone:
	bash run_standalone.sh

## short: run short sweep for testing
short:
	bash run_short.sh

## sweep: run sweep
sweep:
	bash run_sweep.sh
