# scale

include ../../examples.mk

## standalone: run invasion percolation
standalone:
	python invperc.py standalone.json

## short: run short sweep for testing
short:
	python flow.py run --sweep short.json

## sweep: run sweep
sweep:
	python flow.py run --sweep sweep.json
