title: Research Software Design by Example
repository: gvwilson/rsdx
author:
  name: Greg Wilson

chapters:
- title: "Initial Script"
  key: script
- title: "Parse Raw Data"
  key: parse
- title: "Geocoded Readings"
  key: center
- title: "Grid Abstraction"
  key: grid
- title: "Measure Performance"
  key: perf
- title: "Task Runner"
  key: flow
- title: "Lazy Algorithm"
  key: lazy
- title: "Measure Fractal Dimension"
  key: dim
- title: "Estimate Density vs. Distance"
  key: density
- title: "Testing"
  key: test

defaults:
- scope:
    path: ""
  values:
    layout: "default"

markdown: kramdown
highlighter: rouge

exclude:
  - CODE_OF_CONDUCT.md
  - LICENSE.md
  - README.md
  - pyproject.toml
  - requirements.txt
  - '.#*'
  - '*~'

permalink: pretty
