[project]
name = "rsdx"
version = "0.1.28"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "html5validator",
    "jinja2",
    "mccole",
    "numpy",
    "polars",
    "pytest",
    "snailz",
    "uvicorn"
]

[tool.ruff.lint.extend-per-file-ignores]
"**/test_*.py" = ["F401", "F811"] # ignore complaints about unused imports for fixtures

[tool.mccole]
skips = ["headers.txt", "info", "old", "templates", "unused", ]
links = "links.md"

[tool.mccole.renames]
"CODE_OF_CONDUCT.md" = "code_of_conduct.md"
"CONTRIBUTING.md" = "contributing.md"
"LICENSE.md" = "license.md"
"README.md" = "index.md"

[tool.uv.workspace]
members = ["rsdx"]
