[project]
name = "rsdx"
version = "0.1.28"
dependencies = [
    "build",
    "click",
    "coverage",
    "dvc",
    "faker",
    "flask",
    "geopy",
    "kaleido",
    "mccole",
    "metaflow",
    "numpy",
    "pandas",
    "pdoc",
    "plotly.express",
    "pony",
    "prettytable",
    "pyalex",
    "pytest",
    "python-dotenv",
    "requests",
    "snailz",
    "sqlmodel",
    "tinydb"
]

[tool.ruff.lint.extend-per-file-ignores]
"**/test_*.py" = ["F401", "F811"] # ignore complaints about unused imports for fixtures

[tool.mccole]
skips = ["example_site", "templates", "unused", "headers.txt"]
links = "info/links.yml"

[tool.mccole.renames]
"CODE_OF_CONDUCT.md" = "code_of_conduct.md"
"CONTRIBUTING.md" = "contributing.md"
"LICENSE.md" = "license.md"
"README.md" = "index.md"
