include ../../examples.mk

## single: run single sweep
.PHONY: single
single:
	python invperc_single.py params_single.json

## small: run small sweep
.PHONY: small
small:
	python invperc_sweep.py params_small.json

## full: run full sweep
.PHONY: full
full:
	python invperc_sweep.py params_full.json
